// Copyright 2019-Present LexLiu. All Rights Reserved.

#pragma once

#include "Core/Components/LexWidget.h"
#include "Core/Components/LexVisual.h"
#include "Core/Components/LexVisualBatchMesh.h"
#include "Core/Components/LexVisualPostProcess.h"
#include "Core/Components/LexCustomMesh.h"
#include "Core/Components/UISpriteBase.h"
#include "Core/Components/UISprite.h"
#include "Core/Components/UITextureBase.h"
#include "Core/Components/UITexture.h"
#include "Core/Components/LexImage.h"
#include "Core/Components/LexRectBlock.h"
#include "Core/Components/LexCanvas.h"
#include "Core/Components/LexText.h"
#include "Core/Components/LexBackgroundBlur.h"
#include "Core/Components/LexBackgroundPixelate.h"
#include "Core/LexUIBehaviour.h"
#include "Core/LexUIBehaviour.h"
#include "Core/ILexUICultureChangedInterface.h"

#include "Core/LexUIFontData_Bitmap.h"
#include "Core/LexUIFontData_BaseObject.h"
#include "Core/LexUIFontData_FreeTypeRender.h"
#include "Core/LexUIDynamicSpriteAtlasData.h"
#include "Core/LexUIStaticSpriteAtlasData.h"
#include "Core/LexUISpriteData.h"
#include "Core/LexUISpriteInfo.h"
#include "Core/LexUISpriteData_BaseObject.h"
#include "Core/LexUIRichTextImageData.h"
#include "Core/LexUIRichTextImageData_BaseObject.h"
#include "Core/LexCustomMeshSource.h"

#include "Core/Actor/LexWidgetActor.h"
#include "Core/LexUIManager.h"

#include "Event/LexEventSystem.h"
#include "Event/Interface/LexPointerClickInterface.h"
#include "Event/Interface/LexPointerDownUpInterface.h"
#include "Event/Interface/LexPointerEnterExitInterface.h"
#include "Event/Interface/LexPointerDragInterface.h"
#include "Event/Interface/LexPointerScrollInterface.h"
#include "Event/Interface/LexPointerDragDropInterface.h"
#include "Event/Interface/LexPointerSelectDeselectInterface.h"
#include "Event/LexDelegateDeclaration.h"
#include "Event/LexPointerEventData.h"
#include "Event/LGUIEventDelegate.h"
#include "Event/LGUIEventDelegate_PresetParameter.h"
#include "Event/LexBaseRaycaster.h"
#include "Event/LexScreenSpaceRaycaster.h"
#include "Event/LexWorldSpaceRaycaster.h"
#include "Event/InputModule/LexBaseInputModule.h"
#include "Event/InputModule/LexPointerInputModule.h"
#include "Event/InputModule/LexStandaloneInputModule.h"
#include "Event/InputModule/LexTouchInputModule.h"

#include "Extensions/UIRing.h"
#include "Extensions/UIPolygon.h"
#include "Extensions/UIPolygonLine.h"
#include "Extensions/LexStaticMesh.h"
#include "Extensions/2DLineRenderer/UI2DLineChildrenAsPoints.h"
#include "Extensions/2DLineRenderer/UI2DLineRaw.h"
#include "Extensions/2DLineRenderer/UI2DLineRendererBase.h"
#include "Extensions/UISpriteSequencePlayer.h"
#include "Extensions/UISpriteSheetTexturePlayer.h"
#include "Extensions/LGUIRenderTargetInteraction.h"
#include "Extensions/LGUIRenderTargetGeometrySource.h"
#include "Extensions/UIWidget.h"
#include "Extensions/UIWidgetInteraction.h"
#include "Extensions/UIRenderTarget.h"
#include "Extensions/LGUIRenderTargetInteraction.h"

#include "GeometryModifier/LexMeshModifierGradientColor.h"
#include "GeometryModifier/LexMeshModifierLongShadow.h"
#include "GeometryModifier/LexMeshModifierOutline.h"
#include "GeometryModifier/LexMeshModifierPositionAsUV.h"
#include "GeometryModifier/LexMeshModifierShadow.h"
#include "GeometryModifier/LexMeshModifierTextAnimation.h"
#include "GeometryModifier/LexMeshModifierBase.h"
#include "GeometryModifier/TextAnimation/LexMeshModifierTextAnimation_PropertyWithEase.h"
#include "GeometryModifier/TextAnimation/LexMeshModifierTextAnimation_PropertyWithWave.h"
#include "GeometryModifier/TextAnimation/LexVisualEffectTextAnimation_Selector.h"

#include "Interaction/UIButtonComponent.h"
#include "Interaction/UIEventBlockerComponent.h"
#include "Interaction/UIEventTriggerComponent.h"
#include "Interaction/UIScrollbarComponent.h"
#include "Interaction/UIScrollViewComponent.h"
#include "Interaction/UIScrollViewWithScrollbarComponent.h"
#include "Interaction/UISelectableComponent.h"
#include "Interaction/UISliderComponent.h"
#include "Interaction/UITextInputComponent.h"
#include "Interaction/UIToggleComponent.h"
#include "Interaction/UIToggleGroupComponent.h"
#include "Interaction/UIDropdownComponent.h"

#include "PrefabSystem/LGUIPrefab.h"
#include "PrefabSystem/LGUIPrefabLevelManagerActor.h"
#include "PrefabSystem/LGUIPrefabManager.h"
#include "PrefabSystem/LGUIPrefabSettings.h"
#include "PrefabSystem/LGUIPrefabHelperObject.h"
#include "PrefabSystem/ILGUIPrefabInterface.h"

#include "Utils/LexUIUtils.h"

#include "LGUIBPLibrary.h"
#include "LGUIComponentReference.h"

#include "PrefabAnimation/LGUIPrefabSequence.h"
#include "PrefabAnimation/LGUIPrefabSequenceComponent.h"