// Copyright 2019-Present LexLiu. All Rights Reserved.

#pragma once

#include "Core/Components/LexWidget.h"
#include "Core/Components/LexVisual.h"
#include "Core/Components/LexVisualBatchMesh.h"
#include "Core/Components/LexVisualPostProcess.h"
#include "Core/Components/UICustomMesh.h"
#include "Core/Components/UISpriteBase.h"
#include "Core/Components/UISprite.h"
#include "Core/Components/UITextureBase.h"
#include "Core/Components/UITexture.h"
#include "Core/Components/LexRectBlock.h"
#include "Core/Components/LexCanvas.h"
#include "Core/Components/LexText.h"
#include "Core/Components/LexBackgroundBlur.h"
#include "Core/Components/LexBackgroundPixelate.h"
#include "Core/LexUIBehaviour.h"
#include "Core/LexUIBehaviour.h"
#include "Core/ILexUICultureChangedInterface.h"

#include "Core/LexUIFontData_Bitmap.h"
#include "Core/LexUIFontData_BaseObject.h"
#include "Core/LexUIFontData_FreeTypeRender.h"
#include "Core/LexUIDynamicSpriteAtlasData.h"
#include "Core/LexUIStaticSpriteAtlasData.h"
#include "Core/LexUISpriteData.h"
#include "Core/LexUISpriteInfo.h"
#include "Core/LexUISpriteData_BaseObject.h"
#include "Core/LexUIRichTextImageData.h"
#include "Core/LexUIRichTextImageData_BaseObject.h"
#include "Core/LGUICustomMesh.h"

#include "Core/Actor/LexWidgetActor.h"
#include "Core/LGUIManager.h"

#include "Event/LGUIEventSystem.h"
#include "Event/Interface/LGUIPointerClickInterface.h"
#include "Event/Interface/LGUIPointerDownUpInterface.h"
#include "Event/Interface/LGUIPointerEnterExitInterface.h"
#include "Event/Interface/LGUIPointerDragInterface.h"
#include "Event/Interface/LGUIPointerScrollInterface.h"
#include "Event/Interface/LGUIPointerDragDropInterface.h"
#include "Event/Interface/LGUIPointerSelectDeselectInterface.h"
#include "Event/LGUIDelegateDeclaration.h"
#include "Event/LGUIPointerEventData.h"
#include "Event/LGUIEventDelegate.h"
#include "Event/LGUIEventDelegate_PresetParameter.h"
#include "Event/LGUIBaseRaycaster.h"
#include "Event/LGUIScreenSpaceRaycaster.h"
#include "Event/LGUIWorldSpaceRaycaster.h"
#include "Event/InputModule/LGUIBaseInputModule.h"
#include "Event/InputModule/LGUI_PointerInputModule.h"
#include "Event/InputModule/LGUI_StandaloneInputModule.h"
#include "Event/InputModule/LGUI_TouchInputModule.h"

#include "Extensions/UIRing.h"
#include "Extensions/UIPolygon.h"
#include "Extensions/UIPolygonLine.h"
#include "Extensions/UIStaticMesh.h"
#include "Extensions/2DLineRenderer/UI2DLineChildrenAsPoints.h"
#include "Extensions/2DLineRenderer/UI2DLineRaw.h"
#include "Extensions/2DLineRenderer/UI2DLineRendererBase.h"
#include "Extensions/UISpriteSequencePlayer.h"
#include "Extensions/UISpriteSheetTexturePlayer.h"
#include "Extensions/LGUIRenderTargetInteraction.h"
#include "Extensions/LGUIRenderTargetGeometrySource.h"
#include "Extensions/UIWidget.h"
#include "Extensions/UIWidgetInteraction.h"
#include "Extensions/UIRenderTarget.h"
#include "Extensions/LGUIRenderTargetInteraction.h"

#include "GeometryModifier/UIEffectGradientColor.h"
#include "GeometryModifier/UIEffectLongShadow.h"
#include "GeometryModifier/UIEffectOutline.h"
#include "GeometryModifier/UIEffectPositionAsUV.h"
#include "GeometryModifier/UIEffectShadow.h"
#include "GeometryModifier/UIEffectTextAnimation.h"
#include "GeometryModifier/LexVisualBatchMeshModifierBase.h"
#include "GeometryModifier/TextAnimation/UIEffectTextAnimation_PropertyWithEase.h"
#include "GeometryModifier/TextAnimation/UIEffectTextAnimation_PropertyWithWave.h"
#include "GeometryModifier/TextAnimation/UIEffectTextAnimation_Selector.h"

#include "Interaction/UIButtonComponent.h"
#include "Interaction/UIEventBlockerComponent.h"
#include "Interaction/UIEventTriggerComponent.h"
#include "Interaction/UIScrollbarComponent.h"
#include "Interaction/UIScrollViewComponent.h"
#include "Interaction/UIScrollViewWithScrollbarComponent.h"
#include "Interaction/UISelectableComponent.h"
#include "Interaction/UISliderComponent.h"
#include "Interaction/UITextInputComponent.h"
#include "Interaction/UIToggleComponent.h"
#include "Interaction/UIToggleGroupComponent.h"
#include "Interaction/UIDropdownComponent.h"

#include "PrefabSystem/LGUIPrefab.h"
#include "PrefabSystem/LGUIPrefabLevelManagerActor.h"
#include "PrefabSystem/LGUIPrefabManager.h"
#include "PrefabSystem/LGUIPrefabSettings.h"
#include "PrefabSystem/LGUIPrefabHelperObject.h"
#include "PrefabSystem/ILGUIPrefabInterface.h"

#include "Utils/LexUIUtils.h"

#include "LGUIBPLibrary.h"
#include "LGUIComponentReference.h"

#include "PrefabAnimation/LGUIPrefabSequence.h"
#include "PrefabAnimation/LGUIPrefabSequenceComponent.h"