// Copyright 2019-Present LexLiu. All Rights Reserved.
#include "/Engine/Public/Platform.ush"

struct VSToPS
{
    float4 position : SV_Position;
    half4 color : COLOR;
};

float4x4 _MVP;
void MainVS(
    in float3 Position:ATTRIBUTE0,
    in half4 Color : ATTRIBUTE1,
    out VSToPS v2p
)
{
    v2p.position = mul(float4(Position.xyz, 1.0), _MVP);
    v2p.color = Color;
}

void MainPS(
    VSToPS input,
    out float4 OutColor : SV_Target0
)
{
    OutColor = input.color;
}
