#include "/Engine/Private/GammaCorrectionCommon.ush"

void LexUI_ReadWidgetProperty_Simple(float2 UV1, Texture2D DataTex
    , inout float FontMark, inout float ClipDataCoordinate
    , inout float2 Size, inout float2 CenterPosition)
{
    //read data from texture
    int Coordinate = round(UV1.x);
    int3 Position = int3(0, Coordinate, 0);

    float4 PixelData = DataTex.Load(Position);Position.x += 1;
    uint ByteUint = asuint(PixelData.x);
    uint FontMarkUint = (ByteUint >> 24) & 0x000000ff;
    FontMark = FontMarkUint;
    ClipDataCoordinate = asuint(PixelData.y);
    Size = PixelData.zw;
    PixelData = DataTex.Load(Position);Position.x += 1;
    CenterPosition = PixelData.xy;
}