#include "/Engine/Private/GammaCorrectionCommon.ush"

#ifndef PI
#define PI 3.14159265359f
#endif

#ifndef INV_PI
#define INV_PI 0.31830988618379f
#endif

#ifndef HALF_PI
#define HALF_PI 1.57079632679f
#endif

#ifndef INV_255
#define INV_255 0.00392156862745f
#endif

#ifndef INV_360
#define INV_360 0.00277777777777f
#endif

half4 LexUI_UnpackUintColor(uint colorUint)
{
    half4 ResultColor;
    ResultColor.r = ((colorUint >> 24) & 0x000000ff) * INV_255;
    ResultColor.g = ((colorUint >> 16) & 0x000000ff) * INV_255;
    ResultColor.b = ((colorUint >> 8) & 0x000000ff) * INV_255;
    ResultColor.a = ((colorUint >> 0) & 0x000000ff) * INV_255;
    return ResultColor;
}
half4 LexUI_ReadColor(float Data)
{
    uint ColorUint = asuint(Data);
    half4 Color = LexUI_UnpackUintColor(ColorUint);
    Color.rgb = sRGBToLinear(Color.rgb);
    return Color;
}

// reference from https://www.shadertoy.com/view/4tGGRm
float LexUI_sdRoundRect(float2 p, float2 b, float4 r)
{
    r.xyzw = min(r.xyzw, min(b.x, b.y));
    r.xy = (p.x > 0.0) ? r.xy : r.wz;
    r.x = (p.y > 0.0) ? r.x : r.y;
    float2 q = abs(p) - b + r.x;
    float d = min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r.x;
    // modified by me
    d = d / fwidth(d);
    d = saturate(0.5 - d);
    return d;
}
float LexUI_sdRoundRectInnerShadow(float2 p, float2 b, float4 r, float shadowSize)
{
    r.xyzw = min(r.xyzw, min(b.x, b.y));
    r.xy = (p.x > 0.0) ? r.xy : r.wz;
    r.x = (p.y > 0.0) ? r.x : r.y;
    float2 q = abs(p) - b + r.x;
    float d = min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r.x;

    d = saturate((0.0 - d) / shadowSize);
    d = 1 - d;
    d = smoothstep(0, 1, d);
    return d;
}
float LexUI_sdRoundRectOuterShadow(float2 p, float2 b, float4 r, float shadowSize)
{
    r.xyzw = min(r.xyzw, min(b.x, b.y));
    r.xy = (p.x > 0.0) ? r.xy : r.wz;
    r.x = (p.y > 0.0) ? r.x : r.y;
    float2 q = abs(p) - b + r.x;
    float d = min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r.x;

    d /= shadowSize;
    d = saturate(1.0 - d);
    d = smoothstep(0, 1, d);
    return d;
}

float LexUI_RadialGradient(float2 uv, float2 quadSize, float2 center, float2 radius, float rotation)
{
    float2 fragCoord = uv * quadSize;
    rotation = radians(rotation);
    float cosAngle = cos(rotation);
    float sinAngle = sin(rotation);
    float2x2 rotationMatrix = float2x2(cosAngle, sinAngle, -sinAngle, cosAngle);
    fragCoord = mul(rotationMatrix, fragCoord - center) + center;

    fragCoord.x = (fragCoord.x - center.x) * radius.y / radius.x + center.x;
    float distToCenter = distance(fragCoord, center);
    distToCenter /= radius.y;
    distToCenter = saturate(distToCenter);
    return distToCenter;
}

float4 LexUI_BlendPremul(float4 bottom, float4 top)
{
#if 0
    half3 outColor;
    half outA = top.a + bottom.a * (1.0f - top.a);
    outColor = (top.rgb * top.a + bottom.rgb * bottom.a * (1.0f - top.a)) / outA;
    if (outA == 0)
        outColor.rgb = 0;
    return half4(outColor, outA);
#else
    bottom.rgb *= bottom.a;
    return top * (1.0 - bottom.a) + bottom;
#endif
}

float LexUI_CalculateBuffer(Texture2D MainTex, SamplerState MainTexSampler, float2 UV0, float2 UV1, float2 UV2, Texture2D DataTex, inout float3 Color, inout float Alpha)
{
    half _TextureScaleMode;
    float4 _CornerRadius;
    float2 _QuadSize;
    
    half _EnableBody;
    half4 _BodyColor;
    float2 _TextureUVCenter;
    half _EnableGradient;
    half4 _GradientColor;
    float2 _GradientCenter;
    float2 _GradientRadius;
    float _GradientRotation;
    
    half _EnableBorder;
    float _BorderWidth;
    half _EnableBorderGradient;
    half4 _BorderColor;
    half4 _BorderGradientColor;
    float2 _BorderGradientCenter;
    float2 _BorderGradientRadius;
    float _BorderGradientRotation;

    half _EnableInnerShadow;
    half4 _InnerShadowColor;
    float _InnerShadowSize;
    float _InnerShadowBlur;
    float2 _InnerShadowOffset;

    half _EnableOuterShadow;
    half4 _OuterShadowColor;
    float _OuterShadowSize;
    float _OuterShadowBlur;
    float2 _OuterShadowOffset;

    half _EnableRadialFill;
    float2 _RadialFillCenter;
    float _RadialFillAngle;
    float _RadialFillRotation;
    
    //read data from texture
    {
        int Coordinate = round(UV1.y);
        int3 Position = int3(0, Coordinate, 0);

        float4 PixelData = DataTex.Load(Position);Position.x += 1;
        uint ByteUint = asuint(PixelData.r);
        uint BoolValues = (ByteUint >> 24) & 0x000000ff;
        _TextureScaleMode = (ByteUint >> 16) & 0x000000ff;
        
        _EnableBody = (BoolValues >> 7) & 1;
        _EnableOuterShadow = (BoolValues >> 6) & 1;
        _EnableGradient = (BoolValues >> 5) & 1;
        _EnableBorder = (BoolValues >> 4) & 1;
        _EnableBorderGradient = (BoolValues >> 3) & 1;
        _EnableInnerShadow = (BoolValues >> 2) & 1;
        _EnableRadialFill = (BoolValues >> 1) & 1;
        
        _QuadSize = PixelData.ba;

        PixelData = DataTex.Load(Position);Position.x += 1;
        _CornerRadius = PixelData;
        PixelData = DataTex.Load(Position);Position.x += 1;
        _BodyColor = LexUI_ReadColor(PixelData.r);
        _TextureUVCenter = PixelData.gb;
        
        _GradientColor = LexUI_ReadColor(PixelData.a);
        PixelData = DataTex.Load(Position);Position.x += 1;
        _GradientCenter = PixelData.xy;
        _GradientRadius = PixelData.zw;
        PixelData = DataTex.Load(Position);Position.x += 1;
        _GradientRotation = PixelData.x;

        _BorderWidth = PixelData.y;
        _BorderColor = LexUI_ReadColor(PixelData.z);
        _BorderGradientColor = LexUI_ReadColor(PixelData.w);
        PixelData = DataTex.Load(Position);Position.x += 1;
        _BorderGradientCenter = PixelData.xy;
        _BorderGradientRadius = PixelData.zw;
        PixelData = DataTex.Load(Position);Position.x += 1;
        _BorderGradientRotation = PixelData.x;
        
        _InnerShadowColor = LexUI_ReadColor(PixelData.y);
        _InnerShadowSize = PixelData.z;
        _InnerShadowBlur = PixelData.w;
        PixelData = DataTex.Load(Position);Position.x += 1;
        _InnerShadowOffset = PixelData.xy;
        
        _RadialFillCenter = PixelData.zw;
        PixelData = DataTex.Load(Position);Position.x += 1;
        _RadialFillRotation = PixelData.x;
        _RadialFillAngle = PixelData.y;
        
        _OuterShadowColor = LexUI_ReadColor(PixelData.z);
        _OuterShadowSize = PixelData.w;
        PixelData = DataTex.Load(Position);Position.x += 1;
        _OuterShadowBlur = PixelData.x;
        _OuterShadowOffset = PixelData.yz;

    }
    
    
    _GradientCenter.y = _QuadSize.y - _GradientCenter.y;
    _BorderGradientCenter.y = _QuadSize.y - _BorderGradientCenter.y;
    _InnerShadowOffset.y = -_InnerShadowOffset.y;
    _OuterShadowOffset.y = -_OuterShadowOffset.y;
    _RadialFillCenter.y = _QuadSize.y - _RadialFillCenter.y;

    half4 color = half4(0,0,0,0);

    float2 sdQuadSize = _QuadSize * 0.5f;
    float2 sdFragCoord = (UV0 * 2.0f - float2(1.0f, 1.0f)) * sdQuadSize;
    float dOuter = LexUI_sdRoundRect(sdFragCoord, sdQuadSize, _CornerRadius);
    
    //outer shadow
    if (_EnableOuterShadow)
    {
        half4 outerShadowColor = _OuterShadowColor;
        float4 cornerRadius = _CornerRadius + _OuterShadowSize;
        float outerShadow = LexUI_sdRoundRectOuterShadow(sdFragCoord - _OuterShadowOffset, sdQuadSize + _OuterShadowSize, cornerRadius, _OuterShadowBlur * 0.5f);
        outerShadowColor.a *= outerShadow;
        float outerMask = 1.0f - dOuter;
        half bodyVisible = sign(_EnableBody + _EnableBorder + _EnableInnerShadow); //is body visible?
        outerShadowColor.a *= lerp(
        outerMask // if body not visible, make it smooth
        , sign(outerMask) //if body is visible, make it no smooth, because smooth can show a thin transparent line between body and outshadow
        , bodyVisible);
        color = LexUI_BlendPremul(color, outerShadowColor);
        //outerShadowColor.rgb *= outerShadowColor.a;
        //color = color * (1.0 - outerShadowColor.a) + outerShadowColor;
    }
    
    //inner body
    if (_EnableBody)
    {
        float2 stretchUV = UV2;
        float2 fitUV = UV2;
        float2 envelopUV = UV2;
        {
            float fitUVX = (UV2.x - _TextureUVCenter.x) * _QuadSize.x / _QuadSize.y + _TextureUVCenter.x;
            float fitUVY = (UV2.y - _TextureUVCenter.y) * _QuadSize.y / _QuadSize.x + _TextureUVCenter.y;
            half lerpAlpha = saturate(sign(_QuadSize.x - _QuadSize.y));
            fitUV = lerp(float2(UV2.x, fitUVY), float2(fitUVX, UV2.y), lerpAlpha);
            envelopUV = lerp(float2(fitUVX, UV2.y), float2(UV2.x, fitUVY), lerpAlpha);
        }
        
        float2 texUV = lerp(lerp(stretchUV, fitUV, _TextureScaleMode), envelopUV, max(0, _TextureScaleMode - 1));
        float4 MainTexColor = Texture2DSample(MainTex, MainTexSampler, texUV);
        float4 bodyColor = MainTexColor * _BodyColor;

        if (_EnableGradient)
        {
            float gradientLerpAlpha = LexUI_RadialGradient(UV0, _QuadSize, _GradientCenter.xy, _GradientRadius.xy, _GradientRotation);
            bodyColor = lerp(_GradientColor * MainTexColor, bodyColor, gradientLerpAlpha);
        }
        
        bodyColor.a *= dOuter;
        color = LexUI_BlendPremul(color, bodyColor);
    }
    
    if (_EnableInnerShadow)
    {
        float2 quadSize = sdQuadSize - _InnerShadowSize + _InnerShadowBlur * 0.5f;
        float4 cornerRadius = _CornerRadius + _InnerShadowBlur * 0.5f - _InnerShadowSize;
        cornerRadius = max(cornerRadius, _InnerShadowBlur);
        float innerShadow = LexUI_sdRoundRectInnerShadow(sdFragCoord - _InnerShadowOffset.xy, quadSize, cornerRadius, _InnerShadowBlur);
        half4 innerShadowColor = _InnerShadowColor;
        innerShadowColor.a *= innerShadow;
        innerShadowColor.a *= dOuter;
        color = LexUI_BlendPremul(color, innerShadowColor);
    }

    if (_EnableBorder * sign(abs(_BorderWidth)))
    {
        half4 borderColor = _BorderColor;
        if (_EnableBorderGradient)
        {
            float borderGradientLerpAlpha = LexUI_RadialGradient(UV0, _QuadSize, _BorderGradientCenter.xy, _BorderGradientRadius.xy, _BorderGradientRotation);
            borderColor = lerp(_BorderGradientColor, borderColor, borderGradientLerpAlpha);
        }
        float dInner = LexUI_sdRoundRect(sdFragCoord, sdQuadSize - _BorderWidth, _CornerRadius - _BorderWidth);
        borderColor.a *= (1.0f - dInner);
        borderColor.a *= dOuter;
        borderColor.a = saturate(borderColor.a);
        color = LexUI_BlendPremul(color, borderColor);
    }

    if (_EnableRadialFill * sign(max(0, 360.0f - _RadialFillAngle)))
    {
        float2 fragCoord = UV0 * _QuadSize;
        float2 centerToPixelDiff = fragCoord - _RadialFillCenter;
        float2 centerToPixelVector = normalize(centerToPixelDiff);

        float rotation = radians(_RadialFillRotation + _RadialFillAngle * 0.5f + 180.0f);
        float cosAngle = cos(rotation);
        float sinAngle = sin(rotation);
        float2x2 rotationMatrix = float2x2(cosAngle, sinAngle, -sinAngle, cosAngle);
        centerToPixelVector = mul(rotationMatrix, centerToPixelVector);
        float angle = atan2(centerToPixelVector.y, centerToPixelVector.x);
        float d = abs(angle * INV_PI);
        d += _RadialFillAngle * INV_360 - 1.0f;
                    
        d /= fwidth(d);
        d = saturate(d);
        color.a *= d;
    }
    color.a *= sign(abs(_QuadSize.x)) * sign(abs(_QuadSize.y));//if size is 0

    Color = color.rgb;
    Alpha = color.a;
    
    return 1;
}