#include "/Engine/Private/GammaCorrectionCommon.ush"

void LexUI_ReadWidgetProperty(float CoordinateInDataTex, Texture2D DataTex
    , inout float FontMark, inout float IsRenderByLexUIRenderer
    , inout float ClipDataCoordinate
    , inout float2 WidgetSize, inout float2 WidgetCenterPosition
    )
{
    //read data from texture
    int Coordinate = round(CoordinateInDataTex);
    int3 Position = int3(0, Coordinate, 0);

    float4 PixelData = DataTex.Load(Position);Position.x += 1;
    uint MarksUint = asuint(PixelData.x);
    uint FontMarkUint = (MarksUint >> 24) & 0x000000ff;
    uint ExtraMarkUint = (MarksUint >> 16) & 0x000000ff;
    
    IsRenderByLexUIRenderer = (ExtraMarkUint >> 7) & 1;    
    FontMark = FontMarkUint;
    ClipDataCoordinate = asuint(PixelData.y);
    WidgetSize = PixelData.zw;
    PixelData = DataTex.Load(Position);Position.x += 1;
    WidgetCenterPosition = PixelData.xy;
}