// Copyright 2026-Present TypeDreamMoon. All Rights Reserved.

#include "Commandlets/DreamGUIReferenceDocsCommandlet.h"

#include "Controls/DreamUIControl.h"
#include "Core/Components/DreamPanelLayouts.h"
#include "Core/Components/DreamPanelSlot.h"
#include "Core/Components/DreamWidget.h"
#include "Core/DreamUIWidgetRegistry.h"
#include "Core/DreamUserWidget.h"

#include "Dom/JsonObject.h"
#include "HAL/FileManager.h"
#include "Interfaces/IPluginManager.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "Misc/FileHelper.h"
#include "Misc/Parse.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "UObject/Class.h"
#include "UObject/UObjectIterator.h"
#include "UObject/UnrealType.h"

DEFINE_LOG_CATEGORY_STATIC(LogDreamGUIReferenceDocs, Log, All);

namespace DreamGUIReferenceDocsLocal
{
	/** One row of a parity table, kept as text: the page prints it and nothing here reasons about it. */
	struct FParityRow
	{
		FString UMGClass;
		FString Member;
		FString Kind;
		FString Status;
		FString Destination;
		FString Note;
	};

	/** Stamped into every page, and what marks a page as this commandlet's to overwrite or remove. */
	const TCHAR* const GeneratedMarker = TEXT("Generated by the DreamGUIReferenceDocs commandlet from reflection.");

	/** "DreamScrollBox" -> the rows of every table that names it as the class its members went to. */
	using FParityIndex = TMap<FString, TArray<FParityRow>>;

	FString StripTypePrefix(const FString& InName)
	{
		if (InName.Len() > 1 && FChar::IsUpper(InName[1])
			&& (InName[0] == TEXT('U') || InName[0] == TEXT('A') || InName[0] == TEXT('F')))
		{
			return InName.RightChop(1);
		}
		return InName;
	}

	void LoadParityTables(const FString& InDirectory, FParityIndex& OutIndex)
	{
		TArray<FString> Files;
		IFileManager::Get().FindFiles(Files, *FPaths::Combine(InDirectory, TEXT("*.json")), true, false);
		Files.Sort();
		for (const FString& File : Files)
		{
			if (File.StartsWith(TEXT("_")))
			{
				continue;
			}
			FString Text;
			TSharedPtr<FJsonObject> Root;
			if (!FFileHelper::LoadFileToString(Text, *FPaths::Combine(InDirectory, File))
				|| !FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Text), Root)
				|| !Root.IsValid())
			{
				UE_LOG(LogDreamGUIReferenceDocs, Warning, TEXT("Skipping %s: it does not parse."), *File);
				continue;
			}
			const FString UMGClass = Root->GetStringField(TEXT("umgClass"));
			const FString DreamClass = StripTypePrefix(Root->GetStringField(TEXT("dreamClass")));
			const TArray<TSharedPtr<FJsonValue>>* Rows = nullptr;
			if (!Root->TryGetArrayField(TEXT("members"), Rows) || Rows == nullptr)
			{
				continue;
			}
			TArray<FParityRow>& Bucket = OutIndex.FindOrAdd(DreamClass);
			for (const TSharedPtr<FJsonValue>& Value : *Rows)
			{
				const TSharedPtr<FJsonObject>* Object = nullptr;
				if (!Value.IsValid() || !Value->TryGetObject(Object) || Object == nullptr)
				{
					continue;
				}
				FParityRow Row;
				Row.UMGClass = UMGClass;
				(*Object)->TryGetStringField(TEXT("umg"), Row.Member);
				(*Object)->TryGetStringField(TEXT("kind"), Row.Kind);
				(*Object)->TryGetStringField(TEXT("status"), Row.Status);
				(*Object)->TryGetStringField(TEXT("dream"), Row.Destination);
				(*Object)->TryGetStringField(TEXT("note"), Row.Note);
				Bucket.Add(MoveTemp(Row));
			}
		}
	}

	/** A tooltip as one table cell: first paragraph, one line, nothing that would end the cell early. */
	FString ToCell(const FString& InText)
	{
		FString Text = InText;
		Text.ReplaceInline(TEXT("\r"), TEXT(""));
		const int32 ParagraphEnd = Text.Find(TEXT("\n\n"));
		if (ParagraphEnd != INDEX_NONE)
		{
			Text.LeftInline(ParagraphEnd);
		}
		Text.ReplaceInline(TEXT("\n"), TEXT(" "));
		Text.ReplaceInline(TEXT("|"), TEXT("\\|"));
		return Text.TrimStartAndEnd();
	}

	FString GetTypeText(const FProperty* InProperty)
	{
		FString Extended;
		const FString Type = InProperty->GetCPPType(&Extended);
		return Type + Extended;
	}

	/** How a Blueprint reaches the property: through a setter, a raw write, a read, or not at all. */
	FString GetBlueprintAccessText(const FProperty* InProperty)
	{
		const FString Setter = InProperty->GetMetaData(TEXT("BlueprintSetter"));
		const FString Getter = InProperty->GetMetaData(TEXT("BlueprintGetter"));
		if (!Setter.IsEmpty())
		{
			return Getter.IsEmpty()
				? FString::Printf(TEXT("`%s`"), *Setter)
				: FString::Printf(TEXT("`%s` / `%s`"), *Getter, *Setter);
		}
		if (InProperty->HasAnyPropertyFlags(CPF_BlueprintVisible))
		{
			return InProperty->HasAnyPropertyFlags(CPF_BlueprintReadOnly) ? TEXT("read only") : TEXT("read / write");
		}
		return TEXT("-");
	}

	FString GetSignatureText(const UFunction* InFunction)
	{
		FString ReturnType = TEXT("void");
		TArray<FString> Parameters;
		for (TFieldIterator<FProperty> It(InFunction); It && It->HasAnyPropertyFlags(CPF_Parm); ++It)
		{
			const FProperty* Parameter = *It;
			if (Parameter->HasAnyPropertyFlags(CPF_ReturnParm))
			{
				ReturnType = GetTypeText(Parameter);
				continue;
			}
			const bool bOut = Parameter->HasAnyPropertyFlags(CPF_OutParm) && !Parameter->HasAnyPropertyFlags(CPF_ConstParm);
			Parameters.Add(FString::Printf(TEXT("%s%s %s"), *GetTypeText(Parameter), bOut ? TEXT("&") : TEXT(""), *Parameter->GetName()));
		}
		return FString::Printf(TEXT("%s %s(%s)"), *ReturnType, *InFunction->GetName(), *FString::Join(Parameters, TEXT(", ")));
	}

	bool IsDocumentedProperty(const FProperty* InProperty)
	{
		return InProperty->HasAnyPropertyFlags(CPF_Edit | CPF_BlueprintVisible)
			&& !InProperty->HasAnyPropertyFlags(CPF_Deprecated)
			&& !InProperty->GetName().StartsWith(TEXT("bOverride_"))
			&& !InProperty->IsA<FMulticastDelegateProperty>();
	}

	/** One page. Own members only: what a class inherits is on the page of the class that declares it. */
	FString WritePage(const UStruct* InType, const TSet<const UStruct*>& InDocumented, const FParityIndex& InParity)
	{
		const UClass* Class = Cast<UClass>(InType);
		const FString CppName = InType->GetPrefixCPP() + InType->GetName();
		FString Page;
		Page += FString::Printf(TEXT("# %s\n\n"), *CppName);
		Page += FString::Printf(TEXT("<!-- %s Edit the header, not this page. -->\n\n"), GeneratedMarker);

		if (const UStruct* Super = InType->GetSuperStruct())
		{
			const FString SuperName = Super->GetPrefixCPP() + Super->GetName();
			Page += InDocumented.Contains(Super)
				? FString::Printf(TEXT("Inherits from [%s](%s.md).\n\n"), *SuperName, *Super->GetName())
				: FString::Printf(TEXT("Inherits from `%s`.\n\n"), *SuperName);
		}
		const FString Header = InType->GetMetaData(TEXT("ModuleRelativePath"));
		if (!Header.IsEmpty())
		{
			Page += FString::Printf(TEXT("Declared in `%s`.\n\n"), *Header);
		}
		const FString Summary = InType->GetToolTipText().ToString();
		if (!Summary.IsEmpty() && Summary != InType->GetName())
		{
			Page += Summary.Replace(TEXT("\r"), TEXT("")) + TEXT("\n\n");
		}

		FString Properties;
		FString Events;
		for (TFieldIterator<FProperty> It(InType, EFieldIteratorFlags::ExcludeSuper); It; ++It)
		{
			const FProperty* Property = *It;
			const FMulticastDelegateProperty* Delegate = CastField<FMulticastDelegateProperty>(Property);
			if (Delegate != nullptr && Property->HasAnyPropertyFlags(CPF_BlueprintAssignable))
			{
				const FString Signature = Delegate->SignatureFunction != nullptr ? GetSignatureText(Delegate->SignatureFunction) : FString();
				Events += FString::Printf(TEXT("| `%s` | `%s` | %s |\n"), *Property->GetName(), *Signature,
					*ToCell(Property->GetToolTipText().ToString()));
			}
			else if (IsDocumentedProperty(Property))
			{
				// An undocumented property's tooltip is its own name, which says nothing a reader lacks.
				FString Description = ToCell(Property->GetToolTipText().ToString());
				if (Description == Property->GetName() || Description == Property->GetDisplayNameText().ToString())
				{
					Description.Reset();
				}
				const bool bPanelEditable = Property->HasAnyPropertyFlags(CPF_Edit) && !Property->HasAnyPropertyFlags(CPF_EditConst);
				Properties += FString::Printf(TEXT("| `%s` | `%s` | %s | %s | %s | %s |\n"), *Property->GetName(), *GetTypeText(Property),
					*Property->GetMetaData(TEXT("Category")), bPanelEditable ? TEXT("yes") : TEXT("-"),
					*GetBlueprintAccessText(Property), *Description);
			}
		}
		if (!Properties.IsEmpty())
		{
			Page += TEXT("## Properties\n\n| Name | Type | Category | In the details panel | From Blueprint | Description |\n|---|---|---|---|---|---|\n");
			Page += Properties + TEXT("\n");
		}

		if (Class != nullptr)
		{
			TArray<const UFunction*> Functions;
			for (TFieldIterator<UFunction> It(Class, EFieldIteratorFlags::ExcludeSuper); It; ++It)
			{
				if (It->HasAnyFunctionFlags(FUNC_BlueprintCallable | FUNC_BlueprintPure | FUNC_BlueprintEvent)
					&& !It->HasAnyFunctionFlags(FUNC_Delegate)
					&& !It->HasMetaData(TEXT("DeprecatedFunction")))
				{
					Functions.Add(*It);
				}
			}
			// Reflection keeps functions in a hash, not in the order the header wrote them.
			Functions.Sort([](const UFunction& A, const UFunction& B) { return A.GetName() < B.GetName(); });
			if (Functions.Num() > 0)
			{
				Page += TEXT("## Functions\n\n| Function | Kind | Description |\n|---|---|---|\n");
				for (const UFunction* Function : Functions)
				{
					const TCHAR* Kind = Function->HasAnyFunctionFlags(FUNC_BlueprintEvent) ? TEXT("event")
						: Function->HasAnyFunctionFlags(FUNC_BlueprintPure) ? TEXT("pure")
						: TEXT("callable");
					Page += FString::Printf(TEXT("| `%s` | %s | %s |\n"), *GetSignatureText(Function), Kind,
						*ToCell(Function->GetToolTipText().ToString()));
				}
				Page += TEXT("\n");
			}
		}
		if (!Events.IsEmpty())
		{
			Page += TEXT("## Events\n\n| Event | Signature | Description |\n|---|---|---|\n");
			Page += Events + TEXT("\n");
		}

		if (const TArray<FParityRow>* Rows = InParity.Find(InType->GetName()))
		{
			Page += TEXT("## Compared with UMG\n\n");
			Page += TEXT("Every Blueprint-facing member of the UMG class, and where it went. *adopt*: same name, same meaning. ")
				TEXT("*map*: here under another name or on another type. *reject*: deliberately absent, with the reason.\n\n");
			Page += TEXT("| UMG | Member | Status | Here | Note |\n|---|---|---|---|---|\n");
			for (const FParityRow& Row : *Rows)
			{
				// An adopted member is here under its own name; the table leaves that cell blank.
				FString Here;
				if (!Row.Destination.IsEmpty())
				{
					Here = FString::Printf(TEXT("`%s`"), *Row.Destination);
				}
				else if (Row.Status == TEXT("adopt"))
				{
					Here = FString::Printf(TEXT("`%s`"), *Row.Member);
				}
				Page += FString::Printf(TEXT("| `%s` | `%s` | %s | %s | %s |\n"), *Row.UMGClass, *Row.Member, *Row.Status,
					*Here, *ToCell(Row.Note));
			}
			Page += TEXT("\n");
		}
		return Page;
	}

	/** Controls with their bases, panels, the slot, the two widget bases, the function libraries, the styles. */
	void CollectDocumentedTypes(TArray<const UStruct*>& OutTypes)
	{
		TArray<FDreamUIWidgetRegistry::FEntry> Entries;
		FDreamUIWidgetRegistry::GetAllEntries(Entries);
		for (const FDreamUIWidgetRegistry::FEntry& Entry : Entries)
		{
			const UClass* Class = Entry.ClassGetter != nullptr ? Entry.ClassGetter() : nullptr;
			for (; Class != nullptr && Class->IsChildOf(UDreamWidget::StaticClass()); Class = Class->GetSuperClass())
			{
				OutTypes.AddUnique(Class);
			}
		}
		const UPackage* RuntimePackage = UDreamWidget::StaticClass()->GetOutermost();
		for (TObjectIterator<UClass> It; It; ++It)
		{
			const UClass* Class = *It;
			if (Class->GetOutermost() != RuntimePackage || !Class->HasAnyClassFlags(CLASS_Native)
				|| Class->HasAnyClassFlags(CLASS_Deprecated | CLASS_NewerVersionExists))
			{
				continue;
			}
			if (Class->IsChildOf(UDreamPanelLayoutBase::StaticClass())
				|| Class->IsChildOf(UDreamPanelSlot::StaticClass())
				|| Class->IsChildOf(UBlueprintFunctionLibrary::StaticClass()))
			{
				OutTypes.AddUnique(Class);
			}
		}
		for (TObjectIterator<UScriptStruct> It; It; ++It)
		{
			const UScriptStruct* Struct = *It;
			const FString StructName = Struct->GetName();
			if (Struct->GetOutermost() == RuntimePackage
				&& (StructName.EndsWith(TEXT("Style")) || StructName.Contains(TEXT("Brush"))
					|| StructName == TEXT("DreamUIStateFaces") || StructName == TEXT("DreamUIWidgetGeometry")))
			{
				OutTypes.AddUnique(Struct);
			}
		}
		// The automation tests declare panels and controls of their own, and reflection cannot tell a
		// fixture from a feature. Where the type was declared can.
		OutTypes.RemoveAll([](const UStruct* Type)
		{
			return Type->GetMetaData(TEXT("ModuleRelativePath")).Contains(TEXT("Tests/"));
		});
		OutTypes.Sort([](const UStruct& A, const UStruct& B) { return A.GetName() < B.GetName(); });
	}

	const TCHAR* GetSectionFor(const UStruct* InType)
	{
		const UClass* Class = Cast<UClass>(InType);
		if (Class == nullptr)
		{
			return TEXT("Styles");
		}
		if (Class->IsChildOf(UBlueprintFunctionLibrary::StaticClass()))
		{
			return TEXT("Function libraries");
		}
		if (Class->IsChildOf(UDreamPanelLayoutBase::StaticClass()) || Class->IsChildOf(UDreamPanelSlot::StaticClass()))
		{
			return TEXT("Panels and slots");
		}
		if (Class->IsChildOf(UDreamUIControl::StaticClass()))
		{
			return TEXT("Controls");
		}
		return TEXT("Widgets");
	}
}

UDreamGUIReferenceDocsCommandlet::UDreamGUIReferenceDocsCommandlet()
{
	IsClient = false;
	IsServer = false;
	IsEditor = true;
	LogToConsole = true;
}

int32 UDreamGUIReferenceDocsCommandlet::Main(const FString& Params)
{
	using namespace DreamGUIReferenceDocsLocal;

	const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("DreamGUI"));
	if (!Plugin.IsValid())
	{
		UE_LOG(LogDreamGUIReferenceDocs, Error, TEXT("The DreamGUI plugin is not mounted."));
		return 1;
	}
	FString OutDirectory;
	if (!FParse::Value(*Params, TEXT("Out="), OutDirectory))
	{
		OutDirectory = FPaths::Combine(Plugin->GetBaseDir(), TEXT("Docs"), TEXT("Reference"));
	}

	FParityIndex Parity;
	LoadParityTables(FPaths::Combine(Plugin->GetBaseDir(), TEXT("Resources"), TEXT("UMGParity")), Parity);

	TArray<const UStruct*> Types;
	CollectDocumentedTypes(Types);
	const TSet<const UStruct*> Documented(Types);

	// Pages that no longer correspond to a type would otherwise outlive it, and a reference that
	// documents a class the plugin no longer has is worse than a missing page. Only pages carrying the
	// generator's own marker are removed: -Out can point anywhere, and whatever else is there stays.
	IFileManager::Get().MakeDirectory(*OutDirectory, true);
	{
		TArray<FString> Stale;
		IFileManager::Get().FindFiles(Stale, *FPaths::Combine(OutDirectory, TEXT("*.md")), true, false);
		for (const FString& File : Stale)
		{
			const FString Path = FPaths::Combine(OutDirectory, File);
			FString Text;
			if (FFileHelper::LoadFileToString(Text, *Path) && Text.Contains(GeneratedMarker))
			{
				IFileManager::Get().Delete(*Path);
			}
		}
	}

	TMap<FString, TArray<FString>> Sections;
	int32 Failures = 0;
	for (const UStruct* Type : Types)
	{
		const FString Path = FPaths::Combine(OutDirectory, Type->GetName() + TEXT(".md"));
		if (!FFileHelper::SaveStringToFile(WritePage(Type, Documented, Parity), *Path, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
		{
			UE_LOG(LogDreamGUIReferenceDocs, Error, TEXT("Could not write %s."), *Path);
			++Failures;
			continue;
		}
		Sections.FindOrAdd(GetSectionFor(Type)).Add(FString::Printf(TEXT("- [%s%s](%s.md)"), Type->GetPrefixCPP(), *Type->GetName(), *Type->GetName()));
	}

	FString Index = FString::Printf(TEXT("# DreamGUI reference\n\n<!-- %s -->\n\n"), GeneratedMarker);
	for (const TCHAR* Section : { TEXT("Controls"), TEXT("Panels and slots"), TEXT("Widgets"), TEXT("Function libraries"), TEXT("Styles") })
	{
		if (const TArray<FString>* Lines = Sections.Find(Section))
		{
			Index += FString::Printf(TEXT("## %s\n\n%s\n\n"), Section, *FString::Join(*Lines, TEXT("\n")));
		}
	}
	if (!FFileHelper::SaveStringToFile(Index, *FPaths::Combine(OutDirectory, TEXT("index.md")), FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
	{
		++Failures;
	}

	UE_LOG(LogDreamGUIReferenceDocs, Display, TEXT("Wrote %d reference pages to %s."), Types.Num() - Failures, *OutDirectory);
	return Failures == 0 ? 0 : 1;
}
